version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - "./backend:/app"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    environment:
      DATABASE_URL: postgres://sammy:password@postgres:5432/scheduler_development
      RAILS_ENV: development

    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sammy
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  db_data: